# Generated by Django 4.1.2 on 2022-11-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_is_admin_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_reviewer",
            field=models.BooleanField(default=False),
        ),
    ]
