# Generated by Django 4.0.8 on 2022-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name (First, Last)'),
        ),
    ]
