# Generated by Django 4.0.8 on 2022-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='terms_adn_condition',
        ),
        migrations.AddField(
            model_name='settings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
