# Generated by Django 4.0.8 on 2022-12-07 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_settings_terms_adn_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='scope_of_works',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='terms_and_conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
