# Generated by Django 4.0.8 on 2022-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_settings_scope_of_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='scope_of_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
