# Generated by Django 4.1.2 on 2022-11-02 07:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechnologyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technology_component",
                    models.CharField(
                        choices=[
                            ("Hardware", "Hardware"),
                            ("Setup", "Setup"),
                            ("Training", "Training"),
                            ("Software", "Software"),
                            ("On Going", "On Going"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "technology_sub_component",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("part_number", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(max_length=1000, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("Per Item", "Per Item"),
                            ("Per IMX Unit", "Per IMX Unit"),
                            ("Per Hour", "Per Hour"),
                            ("Per Licence/Year", "Per Licence/Year"),
                            ("Per Project", "Per Project"),
                            ("Per Software", "Per Software"),
                            ("Per Point/Month", "Per Point/Month"),
                            ("Per Gateway", "Per Gateway"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "distribution_cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "USD")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "distribution_cost",
                    djmoney.models.fields.MoneyField(
                        currency_choices=(("USD", "USD"),),
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "end_user_cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "USD")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "end_user_cost",
                    djmoney.models.fields.MoneyField(
                        currency_choices=(("USD", "USD"),),
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "technology_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="techno_options",
                        to="technologyoptions.technologyoption",
                    ),
                ),
            ],
        ),
    ]
