# Generated by Django 4.1.2 on 2022-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technologyoptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="part_number",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
