# Generated by Django 4.1.2 on 2022-11-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technologyoptions", "0002_alter_technology_part_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TechnologyOption",
            new_name="TechnologyType",
        ),
        migrations.RenameField(
            model_name="technologytype",
            old_name="option",
            new_name="type",
        ),
    ]
