# Generated by Django 4.1.2 on 2022-11-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("technologyoptions", "0003_rename_technologyoption_technologytype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="technology_component",
            field=models.CharField(
                choices=[
                    ("1-Hardware", "1-Hardware"),
                    ("2-Setup", "2-Setup"),
                    ("3-Training", "3-Training"),
                    ("4-Software", "4-Software"),
                    ("5-Ongoing", "5-OnGoing"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="technology_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techno_options",
                to="technologyoptions.technologytype",
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Per Item", "Per Item"),
                    ("Per IMX Unit", "Per IMX Unit"),
                    ("Per Hour", "Per Hour"),
                    ("Per Licence / Year", "Per Licence / Year"),
                    ("Per Project", "Per Project"),
                    ("Per Software", "Per Software"),
                    ("Per Point/ Month", "Per Point/Month"),
                    ("Per Gateway", "Per Gateway"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
