# Generated by Django 4.1.2 on 2022-11-11 05:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("technologyoptions", "0004_alter_technology_technology_component_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnologyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "technology_component",
                    models.CharField(
                        choices=[
                            ("1-Hardware", "1-Hardware"),
                            ("2-Setup", "2-Setup"),
                            ("3-Training", "3-Training"),
                            ("4-Software", "4-Software"),
                            ("5-Ongoing", "5-OnGoing"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "part_number",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("description", models.TextField(max_length=1000, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("Per Item", "Per Item"),
                            ("Per IMX Unit", "Per IMX Unit"),
                            ("Per Hour", "Per Hour"),
                            ("Per Licence / Year", "Per Licence / Year"),
                            ("Per Project", "Per Project"),
                            ("Per Software", "Per Software"),
                            ("Per Point/ Month", "Per Point/Month"),
                            ("Per Gateway", "Per Gateway"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "distribution_cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "USD")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "distribution_cost",
                    djmoney.models.fields.MoneyField(
                        currency_choices=(("USD", "USD"),),
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "end_user_cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "USD")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "end_user_cost",
                    djmoney.models.fields.MoneyField(
                        currency_choices=(("USD", "USD"),),
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechnologySubComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "technology_component",
                    models.CharField(
                        choices=[
                            ("1-Hardware", "1-Hardware"),
                            ("2-Setup", "2-Setup"),
                            ("3-Training", "3-Training"),
                            ("4-Software", "4-Software"),
                            ("5-Ongoing", "5-OnGoing"),
                        ],
                        max_length=255,
                    ),
                ),
                ("sublist_item_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "TechnologySubComponent",
                "verbose_name_plural": "TechnologySubComponents",
            },
        ),
        migrations.AddField(
            model_name="technologytype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="technologytype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="technologytype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
        migrations.AddField(
            model_name="technologysubcomponent",
            name="technology_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technology_sub_components",
                to="technologyoptions.technologytype",
            ),
        ),
        migrations.AddField(
            model_name="technologyoption",
            name="technology_sub_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technology_option_subcomponent",
                to="technologyoptions.technologysubcomponent",
            ),
        ),
        migrations.AddField(
            model_name="technologyoption",
            name="technology_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technology_options",
                to="technologyoptions.technologytype",
            ),
        ),
    ]
