# Generated by Django 4.0.8 on 2022-11-20 03:07

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0006_technologytype_image_technologytype_intro_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyoption',
            name='ps_cost',
            field=djmoney.models.fields.MoneyField(currency_choices=(('USD', 'USD'),), decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='technologyoption',
            name='ps_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
