# Generated by Django 4.0.8 on 2022-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0007_technologyoption_ps_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyoption',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'OnGoing')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technologysubcomponent',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'OnGoing')], max_length=255),
        ),
    ]
