# Generated by Django 4.0.8 on 2022-11-28 13:00

from decimal import Decimal

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "technologyoptions",
            "0008_alter_technologyoption_technology_component_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="technologyoption",
            name="distribution_cost",
            field=djmoney.models.fields.MoneyField(
                currency_choices=(("USD", "USD"),),
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=10,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="technologyoption",
            name="end_user_cost",
            field=djmoney.models.fields.MoneyField(
                currency_choices=(("USD", "USD"),),
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=10,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="technologyoption",
            name="ps_cost",
            field=djmoney.models.fields.MoneyField(
                currency_choices=(("USD", "USD"),),
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=10,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
    ]
