# Generated by Django 4.0.8 on 2022-11-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0009_alter_technologyoption_distribution_cost_and_more'),
        ('technologyoptions', '0009_alter_technologyoption_technology_sub_component'),
    ]

    operations = [
    ]
