# Generated by Django 4.0.8 on 2022-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0010_merge_20221128_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyoption',
            name='part_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
