# Generated by Django 4.0.8 on 2022-12-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0011_alter_technologyoption_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyoption',
            name='distribution_cost_currency',
        ),
        migrations.RemoveField(
            model_name='technologyoption',
            name='end_user_cost_currency',
        ),
        migrations.RemoveField(
            model_name='technologyoption',
            name='ps_cost_currency',
        ),
        migrations.AlterField(
            model_name='technologyoption',
            name='distribution_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='technologyoption',
            name='end_user_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='technologyoption',
            name='ps_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
