# Generated by Django 4.0.8 on 2022-12-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0012_alter_technologytype_intro_para'),
        ('technologyoptions', '0012_remove_technologyoption_distribution_cost_currency_and_more'),
    ]

    operations = [
    ]
