# Generated by Django 4.0.8 on 2022-12-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0013_merge_20221208_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyoption',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'On Going')], max_length=255, null=True, verbose_name='Technology / Service Component'),
        ),
        migrations.AlterField(
            model_name='technologyoption',
            name='technology_sub_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technology_options', to='technologyoptions.technologysubcomponent', verbose_name='Technology / Service Sub Component'),
        ),
        migrations.AlterField(
            model_name='technologyoption',
            name='technology_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technology_options', to='technologyoptions.technologytype', verbose_name='Technology / Service'),
        ),
        migrations.AlterField(
            model_name='technologysubcomponent',
            name='sublist_item_name',
            field=models.CharField(max_length=255, verbose_name='Technology / Service Sub Component'),
        ),
        migrations.AlterField(
            model_name='technologysubcomponent',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'On Going')], max_length=255, verbose_name='Technology / Service Component'),
        ),
        migrations.AlterField(
            model_name='technologysubcomponent',
            name='technology_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technology_sub_components', to='technologyoptions.technologytype', verbose_name='Technology / Service'),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='intro_para',
            field=models.TextField(null=True, verbose_name='Introduction Paragraph'),
        ),
        migrations.AlterField(
            model_name='technologytype',
            name='type',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Technology / Service'),
        ),
    ]
