# Generated by Django 4.0.8 on 2022-12-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "technologyoptions",
            "0014_alter_technologyoption_technology_component_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="technologyoption",
            name="category",
            field=models.CharField(
                choices=[("one off", "One Off"), ("on going", "On Going")],
                max_length=30,
                null=True,
            ),
        ),
    ]
