# Generated by Django 4.0.8 on 2022-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyoptions', '0015_technologyoption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyoption',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'Analytics and Reporting')], max_length=255, null=True, verbose_name='Technology / Service Component'),
        ),
        migrations.AlterField(
            model_name='technologysubcomponent',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'Analytics and Reporting')], max_length=255, verbose_name='Technology / Service Component'),
        ),
    ]
