# Generated by Django 4.1.2 on 2022-11-15 10:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="doc_file",
            field=models.FileField(
                blank=True,
                upload_to="quotations/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[".doc", ".docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="kick_off_fee",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=(("USD", "USD"),),
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quotation_type",
            field=models.CharField(
                choices=[
                    ("Lump Sum", "Lump Sum"),
                    ("Itemized", "Itemized"),
                    ("Subscription Based", "Subscription Based"),
                ],
                default="Lump Sum",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_quotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="subscription_months",
            field=models.IntegerField(blank=True, default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="user_type",
            field=models.CharField(
                choices=[("Distributor", "Distributor"), ("Client", "Client")],
                default="Distributor",
                max_length=12,
            ),
        ),
    ]
