# Generated by Django 4.1.2 on 2022-11-17 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("technologyoptions", "0006_technologytype_image_technologytype_intro_para"),
        ("quotations", "0002_alter_quotation_doc_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotationtechnologyoption",
            old_name="cost",
            new_name="selling_cost",
        ),
        migrations.RenameField(
            model_name="quotationtechnologyoption",
            old_name="cost_currency",
            new_name="selling_cost_currency",
        ),
        migrations.RenameField(
            model_name="quotationthirdpartyitem",
            old_name="cost",
            new_name="selling_cost",
        ),
        migrations.RenameField(
            model_name="quotationthirdpartyitem",
            old_name="cost_currency",
            new_name="selling_cost_currency",
        ),
        migrations.RenameField(
            model_name="thirdpartyitem",
            old_name="cost",
            new_name="selling_cost",
        ),
        migrations.RenameField(
            model_name="thirdpartyitem",
            old_name="cost_currency",
            new_name="selling_cost_currency",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="doc_file",
        ),
        migrations.AddField(
            model_name="quotation",
            name="approved_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_quotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="scope_of_work",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="terms_and_conditions",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="quotationtechnologyoption",
            name="comment",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quotationtechnologyoption",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Per Item", "Per Item"),
                    ("Per IMX Unit", "Per IMX Unit"),
                    ("Per Hour", "Per Hour"),
                    ("Per Licence / Year", "Per Licence / Year"),
                    ("Per Project", "Per Project"),
                    ("Per Software", "Per Software"),
                    ("Per Point/ Month", "Per Point/Month"),
                    ("Per Gateway", "Per Gateway"),
                ],
                default="Per Item",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="quotationthirdpartyitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Per Item", "Per Item"),
                    ("Per IMX Unit", "Per IMX Unit"),
                    ("Per Hour", "Per Hour"),
                    ("Per Licence / Year", "Per Licence / Year"),
                    ("Per Project", "Per Project"),
                    ("Per Software", "Per Software"),
                    ("Per Point/ Month", "Per Point/Month"),
                    ("Per Gateway", "Per Gateway"),
                ],
                default="Per Item",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartyitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Per Item", "Per Item"),
                    ("Per IMX Unit", "Per IMX Unit"),
                    ("Per Hour", "Per Hour"),
                    ("Per Licence / Year", "Per Licence / Year"),
                    ("Per Project", "Per Project"),
                    ("Per Software", "Per Software"),
                    ("Per Point/ Month", "Per Point/Month"),
                    ("Per Gateway", "Per Gateway"),
                ],
                default="Per Item",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="subscription_months",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name="QuotationIntroPara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_para", models.TextField(null=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_introduction_para",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "technology_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="technologyoptions.technologytype",
                    ),
                ),
            ],
        ),
    ]
