# Generated by Django 4.0.8 on 2022-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_rename_cost_quotationtechnologyoption_selling_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='user_type',
            field=models.CharField(choices=[('distributor', 'Distributor'), ('end_user', 'End User')], default='distributor', max_length=12),
        ),
    ]
