# Generated by Django 4.0.8 on 2022-11-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quotationtechnologyoption_ps_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationtechnologyoption',
            name='part_number',
            field=models.CharField(max_length=80),
        ),
    ]
