# Generated by Django 4.0.8 on 2022-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_alter_quotation_quotation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting for approval', 'Waiting for Approval'), ('completed', 'Completd')], default='draft', max_length=30),
        ),
    ]
