# Generated by Django 4.0.8 on 2022-11-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_quotationthirdpartyitem_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartyitem',
            name='comment',
        ),
    ]
