# Generated by Django 4.0.8 on 2022-11-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_quotation_is_approved_quotation_quotation_number_and_more'),
        ('quotations', '0010_remove_thirdpartyitem_comment'),
    ]

    operations = [
    ]
