# Generated by Django 4.0.8 on 2022-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_alter_quotationtechnologyoption_technology_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting for approval', 'Waiting for Approval'), ('completed', 'Completed')], default='draft', max_length=30),
        ),
    ]
