# Generated by Django 4.0.8 on 2022-11-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_alter_quotation_status'),
        ('quotations', '0013_alter_quotationtechnologyoption_unique_together_and_more'),
    ]

    operations = [
    ]
