# Generated by Django 4.0.8 on 2022-11-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_merge_20221128_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationintropara',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_introduction_para', to='quotations.quotation'),
        ),
        migrations.AlterField(
            model_name='quotationtechnologyoption',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_technology_options', to='quotations.quotation'),
        ),
        migrations.AlterField(
            model_name='quotationthirdpartyitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_third_party_items', to='quotations.quotation'),
        ),
    ]
