# Generated by Django 4.0.8 on 2022-11-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_alter_quotationintropara_quotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20, verbose_name='Customer Name')),
                ('position', models.CharField(max_length=20, verbose_name='Customer Position')),
                ('company_name', models.CharField(max_length=20, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=120, verbose_name='Company Address')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_company_address',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_company_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer_position',
        ),
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.client'),
            preserve_default=False,
        ),
    ]
