# Generated by Django 4.0.8 on 2022-12-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_client_remove_quotation_customer_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='kick_off_fee_currency',
        ),
        migrations.RemoveField(
            model_name='quotationtechnologyoption',
            name='ps_cost_currency',
        ),
        migrations.RemoveField(
            model_name='quotationtechnologyoption',
            name='selling_cost_currency',
        ),
        migrations.RemoveField(
            model_name='quotationthirdpartyitem',
            name='ps_cost_currency',
        ),
        migrations.RemoveField(
            model_name='quotationthirdpartyitem',
            name='selling_cost_currency',
        ),
        migrations.RemoveField(
            model_name='thirdpartyitem',
            name='ps_cost_currency',
        ),
        migrations.RemoveField(
            model_name='thirdpartyitem',
            name='selling_cost_currency',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='kick_off_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationtechnologyoption',
            name='ps_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationtechnologyoption',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationthirdpartyitem',
            name='ps_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotationthirdpartyitem',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thirdpartyitem',
            name='ps_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thirdpartyitem',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
