# Generated by Django 4.0.8 on 2022-12-07 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_client_remove_quotation_customer_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='scope_of_work',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='terms_and_conditions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='quotationintropara',
            name='intro_para',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
