# Generated by Django 4.0.8 on 2022-12-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_remove_quotation_kick_off_fee_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='kick_off_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
