# Generated by Django 4.0.8 on 2022-12-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_alter_quotationtechnologyoption_selling_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationthirdpartyitem',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
