# Generated by Django 4.0.8 on 2022-12-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_alter_quotationthirdpartyitem_selling_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartyitem',
            name='quantity',
        ),
    ]
