# Generated by Django 4.0.8 on 2022-12-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_alter_quotation_scope_of_work_and_more'),
        ('quotations', '0021_remove_thirdpartyitem_quantity'),
    ]

    operations = [
    ]
