# Generated by Django 4.0.8 on 2022-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_merge_20221208_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='scope_of_work',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quotationintropara',
            name='intro_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quotationtechnologyoption',
            name='technology_component',
            field=models.CharField(choices=[('1-Hardware', 'Hardware'), ('2-Setup', 'Setup'), ('3-Training', 'Training'), ('4-Software', 'Software'), ('5-Ongoing', 'On Going')], max_length=255),
        ),
    ]
