# Generated by Django 4.0.8 on 2022-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_alter_client_name_alter_quotation_scope_of_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
