# Generated by Django 4.0.8 on 2022-12-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0024_quotation_description_quotation_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_intropara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_scope_of_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_terms_and_condition',
            field=models.BooleanField(default=False),
        ),
    ]
