# Generated by Django 4.0.8 on 2022-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0025_quotation_is_background_quotation_is_intropara_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationtechnologyoption",
            name="category",
            field=models.CharField(
                choices=[("one off", "One Off"), ("on going", "On Going")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quotationtechnologyoption",
            name="technology_component",
            field=models.CharField(
                choices=[
                    ("1-Hardware", "Hardware"),
                    ("2-Setup", "Setup"),
                    ("3-Training", "Training"),
                    ("4-Software", "Software"),
                    ("5-Ongoing", "Analytics and Reporting"),
                ],
                max_length=255,
            ),
        ),
    ]
