# Generated by Django 4.0.8 on 2022-12-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0026_quotationtechnologyoption_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='is_background',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='is_intropara',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='is_scope_of_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='is_terms_and_condition',
            field=models.BooleanField(default=True),
        ),
    ]
